---
title: "Melbourne Housing Market - Paper2"
subtitle: "Intro Data Science"
author: "Team 2"
date: "`r Sys.Date()`"
output:
   html_document:
     toc: true
     toc_float: true
     number_section: true
---



```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
knitr::opts_chunk$set(echo = F)
options(scientific=T, digits = 5) 
options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times

source("general_support.R", local = knitr::knit_global())
source("P2_support.R", local = knitr::knit_global())

```


```{r stats_libs, include=F}
# loadPkg("leaps")
# loadPkg("ggplot2")
# loadPkg("gridExtra")
# loadPkg("scales")
# loadPkg("heatmaply")
# loadPkg("Hmisc")
# loadPkg("faraway")
# loadPkg("jtools")
```


```{r data, include=F}

train <- load_data()
test <- load_data(F)

```




















```{r close_stats_libs, include=F}
# unloadPkg(leaps)
# unloadPkg(ggplot2)
# unloadPkg(gridExtra)
# unloadPkg(scales)
# unloadPkg(heatmaply)
# unloadPkg(Hmisc)
# unloadPkg(faraway)
# unloadPkg(jtools)
```